theme: jekyll-theme-cayman
plugins:
  - jekyll-analytics
jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-1745272-7        # Required - replace with your tracking id